model_providers:
  openrouter:
    api_key: "${OPENROUTER_API_KEY}"
    provider: openrouter
    base_url: https://openrouter.ai/api/v1
    type: cloud
  ollama:
    provider: ollama
    base_url: http://localhost:11434/api
    model: llama3
    type: local
    required: true
  qwen:
    provider: qwen
    type: cloud
    base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
    required: false
    api_key: "${DASHSCOPE_API_KEY}"
    model: qwen-turbo
agent_instances:
  default:
    model: qwen
    tools:
      - bash
      - file
      - http
    sandbox: true
